# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0008_auto_20160209_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estaciondeservicio',
            options={'managed': False},
        ),
    ]
