# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0009_auto_20160209_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estaciondeservicio',
            options={'managed': True},
        ),
    ]
