# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0010_auto_20160223_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restricciones',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('to_cost', models.FloatField(blank=True, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('via_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restricciones',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='estaciondeservicio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='eventoruta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rutastunja',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rutastunjaverticespgr',
            options={'managed': False},
        ),
    ]
